version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - ENV=production
      - PYTHONUNBUFFERED=1
      - PUBLIC_HOST=${PUBLIC_HOST:-localhost}  # Can be overridden with real domain
      - PUBLIC_PROTOCOL=${PUBLIC_PROTOCOL:-http}
      - PUBLIC_PORT=${PUBLIC_PORT:-80}
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./backend/bots:/app/bots  # Ensure bot files are persisted
      - ./backend/template:/app/template  # Ensure templates are available
      - ./persistent_data:/app/persistent_data  # Add persistent data volume
    networks:
      - app-network

  frontend-static:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      # Create a named volume for Nginx to serve the frontend files
      - frontend_data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST:-localhost}
      - PUBLIC_PROTOCOL=${PUBLIC_PROTOCOL:-http}
      - PUBLIC_PORT=${PUBLIC_PORT:-80}
      - FRONTEND_SOURCE_DIR=/frontend_source
    networks:
      - app-network

volumes:
  frontend_data:

networks:
  app-network:
    driver: bridge 